function(unset_variables)
    string(CONCAT one_options "PREFIX")
    cmake_parse_arguments(unset_variables "${bool_options}" "${one_options}" "${list_options}" ${ARGN}) 
    
    set(prefix ${unset_variables_PREFIX})

    unset(l_prefix)
    if (NOT "${EMPTY}${prefix}" STREQUAL "${EMPTY}")
        set(l_prefix ${prefix})
    elseif (DEFINED TEST_PREFIX)
        set(l_prefix ${TEST_PREFIX})
    else()
        set(l_prefix "")
    endif()

    if (NOT "${EMPTY}${l_prefix}" STREQUAL "${EMPTY}")
        string(TOUPPER "${l_prefix}" l_prefix_upper)
        set(TEST_PREFIX ${prefix} CACHE INTERNAL "Test prefix string" FORCE)
        set(TEST_PREFIX_UPPER_ "${l_prefix_upper}_" CACHE INTERNAL "Test prefix string" FORCE)
        unset(l_prefix_upper)
    else()
        set(TEST_PREFIX "" CACHE INTERNAL "Test prefix string" FORCE)
        set(TEST_PREFIX_UPPER_ "" CACHE INTERNAL "Test prefix string" FORCE)
    endif()

    unset(${TEST_PREFIX_UPPER_}TEST_ENABLE_TESTING CACHE)
    unset(${TEST_PREFIX_UPPER_}TEST_INCLUDE_DIR CACHE)
    unset(${TEST_PREFIX_UPPER_}TEST_SRC_DIR CACHE)
    unset(${TEST_PREFIX_UPPER_}TEST_TEST_SRC_DIR CACHE)
    unset(${TEST_PREFIX_UPPER_}TEST_EXTERNAL_DIR CACHE)
    unset(${TEST_PREFIX_UPPER_}TEST_USING_BUILD_UTILS CACHE)
    unset(${TEST_PREFIX_UPPER_}TEST_BUILD_UTILS_ENABLE_TESTING CACHE)
    unset(${TEST_PREFIX_UPPER_}TEST_BUILD_UTILS_DIR CACHE)
    unset(${TEST_PREFIX_UPPER_}TEST_BUILD_UTILS_VERSION CACHE)
    unset(${TEST_PREFIX_UPPER_}TEST_COMPILE_OPTIONS CACHE)
    unset(${TEST_PREFIX_UPPER_}LIST_COMPILE_OPTION_ARG CACHE)
    unset(TEST_CMAKE_BASE_SRC_DIR CACHE)
    unset(TEST_PREFIX CACHE)
    unset(TEST_PREFIX_UPPER_ CACHE)

endif(unset_variables)
