
name: beta-windows_Win32

on:
  push:
    branches: [ beta ]
jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: beta
        submodules: true

    - name: Create build directory
      run: mkdir -p .build

    - name: Generate project
      run: cmake ../cmake -G "Visual Studio 16 2019" -A Win32
      working-directory: ./.build

    - name: Get MsBuild 
      run: echo "::add-path::$(vswhere -latest -requires Microsoft.Component.MSBuild -find MSBuild\**\Bin\MSBuild.exe)"
      shell: pwsh

    - name: Build
      run: msbuild ALL_BUILD.vcxproj /p:Configuration=Debug /p:Platform=X86
      working-directory: ./.build
      shell: powershell

    - name: Test
      run: msbuild RUN_TESTS.vcxproj /p:Configuration=Debug /p:Platform=X86
      working-directory: ./.build
      shell: powershell
