
name: beta-windows

on:
  push:
    branches: [ beta ]
jobs:
  build_test:
    runs-on: windows-latest
    strategy:
      matrix:
        platform: [Win32]
    steps:
    - uses: actions/checkout@v2
      with:
        ref: beta
        submodules: true

    - name: Get msbuild executable
      id: get_msbuild_executable
      run: echo "::set-output name=path::$(vswhere -latest -requires Microsoft.Component.MSBuild -find MSBuild\**\Bin\MSBuild.exe)"

    - name: Create build directory
      run: mkdir -p .build

    - name: Print get_msbuild outputs
      run: echo "${{steps.get_msbuild_executable.outputs.path}}"

    - name: Generate project
      run: cmake ../cmake -G "Visual Studio 16 2019" -A ${{ matrix.platform }}
      working-directory: ./.build

    - name: Build
      run: |
        "${{steps.get_msbuild_executable.outputs.path}}" ALL_BUILD.vcxproj /p:Configuration=Debug /p:Platform=X86
      working-directory: ./.build
      shell: powershell

    - name: Test
      run: |
        "${{steps.get_msbuild_executable.outputs.path}}" RUN_TESTS.vcxproj /p:Configuration=Debug /p:Platform=X86
      working-directory: ./.build
      shell: powershell
