
name: beta-windows

on:
  push:
    branches: [ beta ]
jobs:
  get_msbuild:
    runs-on: windows-latest
    outputs:
      executable: ${{steps.set_executable.outputs.}}
    steps:
      - id: set_executable
        run: echo "::set-output name=matrix::$(vswhere -latest -requires Microsoft.Component.MSBuild -find MSBuild\**\Bin\MSBuild.exe)"
  build_test:
    runs-on: windows-latest
    needs: get_msbuild
    steps:
    - uses: actions/checkout@v2
      with:
        ref: beta
        submodules: true

    - name: Create build directory
      run: mkdir -p .build

    - name: Print get_msbuild outputs
      run: echo ${{get_msbuild.outputs.executable}}

    - name: Generate project
      run: cmake ../cmake -G "Visual Studio 16 2019" -A Win32
      working-directory: ./.build

    - name: Build
      run: |
        $MSBUILD = (vswhere -latest -requires Microsoft.Component.MSBuild -find MSBuild\**\Bin\MSBuild.exe)
        & $MSBUILD ALL_BUILD.vcxproj /p:Configuration=Debug /p:Platform=X86
      working-directory: ./.build
      shell: powershell

    - name: Test
      run: |
        $MSBUILD = (vswhere -latest -requires Microsoft.Component.MSBuild -find MSBuild\**\Bin\MSBuild.exe)
        & $MSBUILD RUN_TESTS.vcxproj /p:Configuration=Debug /p:Platform=X86
      working-directory: ./.build
      shell: powershell
