
name: Msys Build Test

on:
  push:
    branches: [ beta ]
jobs:
  build_test:
    runs-on: windows-latest
    strategy:
      matrix:
        compiler: [GNU]
        platform: [x32, x64]
    steps:
    - uses: actions/checkout@v2
      with:
        ref: beta
        submodules: true

    - name: Create build directory
      run: mkdir -p .build

    - name: Check dir
      run: |
        ls C:\msys64
        ls C:\msys64\usr\bin
        ls C:\msys64\mingw32\bin
        ls C:\msys64\mingw64\bin
      shell: powershell
      if: ${{ matrix.compiler == 'GNU' && matrix.platform == 'x32' }}



